### ISSUE TITLE
User Notifications and Tracking (internal and external)

### ISSUE THREAD

**Issue by mattroush** [CUCentralAdvancement/adr-docs#11]
SendGrid has long been used as the mail system for system-generated emails from the giving website via an account paid for and managed by the Advancement IT system. Until recently, SMTP was used for the integration with SendGrid. In early 2021, SendGrid announced that it was deprecating this method on March 24, 2021 and forcing all clients to use the SendGrid API. This change on D7 site is capture in issue [93 - SendGrid switch to API keys for authentication](https://github.com/CUCentralAdvancement/cu-giving/issues/93).

The assumption has been that SendGrid would remain the email delivery system used in Heroku. However, there have been some recent issues with integration timeouts and deliverability that have lead Digital Engagement to wonder if another service is worth consideration.

## Required

**Which project area is this ADR for?**

- giving.cu.edu backend in both D7 and Heroku.
- potentially affects Advancement Salesforce org/Ascend as SendGrid has been mentioned as the platform of choice for its system-generated emails, as well.

**Which other ADRs does this proposal involve?**

None to-date.

**List where documentation needs to change if the ADR is accepted**

Formal documentation will need to be created.

**Comment by alexfinnarn** [comment]
I added "tracking" to the title since I think https://github.com/CUCentralAdvancement/cu-giving/issues/88 relates to this line of work...sure they could be made into two discrete ones but this was about to get the Stalebot warning anyways.

It's really the decisions on infrastructure/services related to the "user journey" or "donation lifecycle" where you might have a drip email campaign that changes the content based on the user's behavior. You need to track that somehow in order to know what email to send to each user.

I'm sure MC has click tracking features but if they integrate with GA, I guess it's probably the user tracking service to rule them all? Rather than having analytics info sit in one/two email services as well as GA.

**Comment by alexfinnarn** [comment]
really old issue.
